/**
 * MAPC (Metropolitan Area Planning Council) municipalities list.
 * Used for "Show MAPC Region Only" filter on the Digital Equity map.
 */
export const MAPC_MUNICIPALITIES = [
  'LEXINGTON', 'EVERETT', 'BELLINGHAM', 'MILLIS', 'ESSEX', 'MEDFORD', 'CONCORD',
  'SOUTHBOROUGH', 'WILMINGTON', 'GLOUCESTER', 'HAMILTON', 'DOVER', 'WALPOLE',
  'WESTWOOD', 'CANTON', 'SHARON', 'NORWOOD', 'STOUGHTON', 'HINGHAM', 'SAUGUS',
  'QUINCY', 'READING', 'BURLINGTON', 'MARLBOROUGH', 'NORFOLK', 'PEMBROKE',
  'NEEDHAM', 'WRENTHAM', 'HUDSON', 'MANCHESTER', 'WELLESLEY', 'MEDFIELD',
  'CAMBRIDGE', 'MARSHFIELD', 'SWAMPSCOTT', 'SOMERVILLE', 'HOLBROOK', 'MEDWAY',
  'WENHAM', 'SALEM', 'NATICK', 'HANOVER', 'LYNN', 'HOLLISTON', 'DUXBURY',
  'WEYMOUTH', 'BELMONT', 'MARBLEHEAD', 'BROOKLINE', 'WESTON', 'WINCHESTER',
  'CARLISLE', 'ARLINGTON', 'SCITUATE', 'ASHLAND', 'CHELSEA', 'MIDDLETON',
  'BOLTON', 'DEDHAM', 'STONEHAM', 'NAHANT', 'LITTLETON', 'WAKEFIELD',
  'MILFORD', 'WINTHROP', 'FRAMINGHAM', 'MELROSE', 'WAYLAND', 'NORWELL',
  'LYNNFIELD', 'IPSWICH', 'STOW', 'COHASSET', 'LINCOLN', 'ACTON', 'WALTHAM',
  'FOXBOROUGH', 'SUDBURY', 'BEVERLY', 'HOPKINTON', 'RANDOLPH', 'MAYNARD',
  'ROCKLAND', 'MILTON', 'REVERE', 'MALDEN', 'BRAINTREE', 'WATERTOWN',
  'PEABODY', 'DANVERS', 'TOPSFIELD', 'WOBURN', 'BILLERICA', 'TEWKSBOROUGH',
  'CHELMSFORD', 'LOWELL', 'DRACUT', 'TYNGSBORO', 'PEPPERELL', 'GROTON', 'AYER',
  'SHIRLEY', 'HARVARD', 'LANCASTER', 'CLINTON', 'BERLIN',
  'WESTBOROUGH', 'NORTHBOROUGH', 'SHREWSBURY', 'GRAFTON',
  'MILLBURY', 'AUBURN', 'OXFORD', 'WEBSTER', 'DOUGLAS', 'UXBRIDGE', 'MENDON',
  'HOPEDALE', 'HULL', 'KINGSTON', 'PLYMOUTH', 'CARVER', 'WAREHAM',
  'BOURNE', 'SANDWICH', 'BARNSTABLE', 'YARMOUTH', 'DENNIS', 'BREWSTER', 'ORLEANS',
  'EASTHAM', 'WELLFLEET', 'TRURO', 'PROVINCETOWN',
];
